# Generated by Django 3.2.7 on 2021-10-27 09:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID покупателя')),
                ('tg_username', models.CharField(blank=True, default='', max_length=50, verbose_name='Имя покупателя в Телеграме')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('GDPR_status', models.BooleanField(default=False, null=True)),
                ('home_address', models.CharField(blank=True, default='', max_length=50, verbose_name='Домашний адрес')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Номер заказа')),
                ('order_price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'Заявка обрабатывается'), ('Готовим ваш торт', 'Готовим ваш торт'), ('Продукт в пути', 'Продукт в пути'), ('Продукт у вас', 'Продукт у вас')], default='Заявка обрабатывается', max_length=256)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Product_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=256)),
                ('parameter_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.product')),
            ],
            options={
                'verbose_name': 'Параметры продукта',
                'verbose_name_plural': 'Параметры продуктов',
            },
        ),
    ]
