# Generated by Django 3.2.7 on 2021-10-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_parameters',
            name='product',
        ),
        migrations.CreateModel(
            name='Productproperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.product')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='product_parameters',
            name='product_property',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.productproperties'),
            preserve_default=False,
        ),
    ]
