# Generated by Django 3.2.7 on 2021-10-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0002_auto_20211027_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproperties',
            options={'verbose_name': 'Свойства Продукта', 'verbose_name_plural': 'Свойства Продуктов'},
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliivery_address',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='product_parameters',
            name='parameter_name',
            field=models.CharField(max_length=256, verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='product_parameters',
            name='product_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.productproperties', verbose_name='Свойства Продукта'),
        ),
    ]
