# Generated by Django 3.2.7 on 2021-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0003_auto_20211027_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliivery_address',
            field=models.CharField(default=' ', max_length=256),
        ),
    ]
