# Generated by Django 3.2.7 on 2021-10-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0005_auto_20211027_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliivery_address',
            new_name='delivery_address',
        ),
    ]
