# Generated by Django 3.2.7 on 2021-10-28 19:43

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0009_auto_20211027_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productproperties',
            new_name='Product_properties',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bake_bot.customer', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=jsonfield.fields.JSONField(default='Пока нет ничего', verbose_name='Детали заказа'),
        ),
    ]
