# Generated by Django 3.2.7 on 2021-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0010_auto_20211028_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.PositiveIntegerField(default=None, verbose_name='Имя Покупателя'),
        ),
    ]
