# Generated by Django 3.2.7 on 2021-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0011_auto_20211028_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя Покупателя'),
        ),
    ]
