# Generated by Django 3.2.7 on 2021-10-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_chat_id',
        ),
    ]
