# Generated by Django 3.2.7 on 2021-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_chat_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat ID Покупателя'),
        ),
    ]
