# Generated by Django 3.2.7 on 2021-10-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bake_bot', '0013_order_customer_chat_id'),
        ('Bake_bot', '0013_rename_customer_order_customer_chat_id'),
    ]

    operations = [
    ]
